/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.innodox.fileviewer.app;

import hu.innodox.fileviewer.app.model.FileProcessingResultTableModel;
import hu.innodox.fileviewer.utils.FileProcessorUtils;
import hu.innodox.fileviewer.worker.FileProcessorWorker;
import hu.innodox.fileviewer.worker.UIRefreshWorker;
import java.awt.Color;
import java.io.File;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Attila
 */
public class Application extends javax.swing.JFrame {

    
    
    private FileProcessingResultTableModel tableModel;
    /**
     * Creates new form Application
     */
    public Application() {
        tableModel = new FileProcessingResultTableModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelContentHolder = new javax.swing.JPanel();
        jScrollPaneProcessedLineTable = new javax.swing.JScrollPane();
        jTableProcessedLines = new javax.swing.JTable();
        jLabelProcessing = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpenFiles = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelContentHolder.setLayout(new javax.swing.BoxLayout(jPanelContentHolder, javax.swing.BoxLayout.LINE_AXIS));

        jTableProcessedLines.setModel(tableModel);
        jScrollPaneProcessedLineTable.setViewportView(jTableProcessedLines);

        jPanelContentHolder.add(jScrollPaneProcessedLineTable);

        getContentPane().add(jPanelContentHolder, java.awt.BorderLayout.CENTER);
        getContentPane().add(jLabelProcessing, java.awt.BorderLayout.PAGE_START);

        jMenuFile.setText("File");

        jMenuItemOpenFiles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOpenFiles.setText("Open files");
        jMenuItemOpenFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenFilesActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpenFiles);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar.add(jMenuFile);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemOpenFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenFilesActionPerformed
     
        
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Select directory to process");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {      
                    
                    this.jLabelProcessing.setText("Processing started!");
                    this.jLabelProcessing.setForeground(Color.RED);
                        
                    this.tableModel.clearModel();
                    this.tableModel.fireTableDataChanged();
                    
                    File[] txtFiles = FileProcessorUtils.finder(chooser.getSelectedFile());
                                    
                    final ExecutorService threadPool = Executors.newFixedThreadPool(txtFiles.length + 1);
                    
                    final UIRefreshWorker uiWorker = new UIRefreshWorker(txtFiles.length, () -> {
                        this.jLabelProcessing.setText("Processing finished!");
                        this.jLabelProcessing.setForeground(Color.BLUE);
                    });
                    
                    threadPool.submit(uiWorker);
                    
                    for(File f : txtFiles){
                    
                         FileProcessorWorker worker = new FileProcessorWorker(f, tableModel,uiWorker);
        
                         threadPool.submit(worker);
                    }
                    
                    threadPool.shutdown();
        } else {
            System.out.println("No Selection ");
        }     
    }//GEN-LAST:event_jMenuItemOpenFilesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelProcessing;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemOpenFiles;
    private javax.swing.JPanel jPanelContentHolder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneProcessedLineTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableProcessedLines;
    // End of variables declaration//GEN-END:variables
}
